name: Tests

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php-versions: [ '7.3', '7.4', '8.0', '8.1' ]
        phpunit-versions: [ '9.5' ]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}, composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Validate Composer json/lock
        run: composer validate --strict

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run Unit Test
        run: composer test
